#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import os
import re
import shutil
import subprocess
import sys
import tomllib
from datetime import datetime
from pathlib import Path


SCRIPT_PATH = Path(__file__).resolve()
REPO_ROOT = SCRIPT_PATH.parents[3]
DEFAULT_CONFIG_SOURCE = REPO_ROOT / "config.example.toml"
TEMPLATES_DIR = SCRIPT_PATH.parents[1] / "templates"
AVAILABLE_SKILLS = (
    "codex-bootstrap",
    "ots-ticket",
    "jira-ticket",
    "cm-review",
    "create-module-knowledge-skills",
    "internal-confluence-page",
    "oncall-investigation",
    "object-store",
    "pr-description",
    "scm-pr",
    "bitbucket-pr",
    "release-check",
    "authZ-permissions-yaml-generator",
)
AVAILABLE_MCP_SERVERS = (
    "stlm-mcp",
    "mcp-dope",
    "chrome-devtools",
    "sqlcl",
    "mcp-atlassian-jira-sd",
    "mcp-atlassian-jira-oci",
    "centralconfluence",
    "playwright",
    "ots",
    "mcp_shepherd",
)
DEFAULT_ENABLED_MCP_SERVERS = AVAILABLE_MCP_SERVERS
MCP_SERVERS_USING_SHARED_HOME = (
    "stlm-mcp",
    "mcp-dope",
    "sqlcl",
    "mcp-atlassian-jira-sd",
    "mcp-atlassian-jira-oci",
    "ots",
    "mcp_shepherd",
)
MCP_SERVERS_REQUIRING_LOG_DIRECTORY = ("stlm-mcp", "mcp-dope")
AVAILABLE_AGENTS_MODES = ("symlink", "copy", "skip")
AVAILABLE_AUTH_STATES = ("ready", "needs-setup")
AVAILABLE_AUTH_SHELLS = ("zsh", "bash")
MCP_ENV_SERVER_NAMES = ("stlm-mcp", "mcp-dope")
SHARED_MODEL_PROVIDER = ""
SHARED_MODEL = "gpt-5.5"
SHARED_PROFILE = "gpt-5-5"
DEFAULT_M2_REPOSITORY = str(Path.home() / ".m2" / "repository")
DEFAULT_BITBUCKET_BASE_URL = "https://bitbucket.example.com"
DEFAULT_BITBUCKET_ENV_FILENAME = "bitbucket-pr.env"
DEFAULT_JIRA_BASE_URL = "https://jira-sd.mc1.oracleiaas.com"
DEFAULT_JIRA_OCI_BASE_URL = "https://jira.oci.oraclecorp.com"
DEFAULT_JIRA_SD_MCP_ENV_FILENAME = ".env"
DEFAULT_JIRA_OCI_MCP_ENV_FILENAME = ".env.jira-oci"
JIRA_MCP_AUTH_ENV_NAMES = ("JIRA_URL", "JIRA_PERSONAL_TOKEN")
GENERATED_JIRA_OCI_MCP_ENV_HEADER = "# Generated by Codex bootstrap for mcp-atlassian-jira-oci."
DEFAULT_SQLCL_PASSWORD_ENV_FILE = "~/.env"
DEFAULT_MCP_ENV_FILENAMES = {
    "stlm-mcp": "mcp.env",
    "mcp-dope": "mcp.env",
}
MCP_ENV_GENERATOR_NAMES = ("stlm-mcp", "mcp-dope")
MCP_ENV_TEMPLATE_FILENAMES = {
    "mcp-dope": "mcp-dope.env.template",
}
AGENTS_RELATIVE_PATHS = (
    "workflows/testing.md",
    "workflows/debugging.md",
    "workflows/feature.md",
    "workflows/refactor.md",
    "workflows/review.md",
    "workflows/release.md",
    "workflows/docs.md",
    "imported_rules/cline_rules/GENERIC_CODE_RULES.md",
    "imported_rules/cline_rules/CLEAN_CODE.md",
    "imported_rules/cline_rules/PR_REVIEW_RULE.md",
    "imported_rules/cline_rules",
    "memory.md",
    "skills/codex-bootstrap/SKILL.md",
    "skills/ots-ticket/SKILL.md",
    "skills/jira-ticket/SKILL.md",
    "skills/cm-review/SKILL.md",
    "skills/create-module-knowledge-skills/SKILL.md",
    "skills/internal-confluence-page/SKILL.md",
    "skills/oncall-investigation/SKILL.md",
    "skills/object-store/SKILL.md",
    "skills/pr-description/SKILL.md",
    "skills/scm-pr/SKILL.md",
    "skills/bitbucket-pr/SKILL.md",
    "skills/release-check/SKILL.md",
    "skills/authZ-permissions-yaml-generator/SKILL.md",
    "skills/pr-description/templates/pr_description.md",
)
PLACEHOLDER_MAP = {
    "/ABSOLUTE/PATH/TO/YOUR/CODEX_HOME": "codex_home",
    "/ABSOLUTE/PATH/TO/YOUR/WORKSPACE_PARENT": "workspace_parent",
    "/ABSOLUTE/PATH/TO/YOUR/M2_REPOSITORY": "m2_repository",
    "/ABSOLUTE/PATH/TO/YOUR/UV_CACHE": "uv_cache",
    "/ABSOLUTE/PATH/TO/YOUR/CHROMIUM_SUPPORT_DIR": "chromium_support_dir",
    "/ABSOLUTE/PATH/TO/YOUR/CHROME_SUPPORT_DIR": "chrome_support_dir",
    "/ABSOLUTE/PATH/TO/YOUR/HOME": "home_dir",
    "/ABSOLUTE/PATH/TO/YOUR/LOG_DIRECTORY": "log_directory",
    "/ABSOLUTE/PATH/TO/THIS/REPO": "repo_root",
    "/ABSOLUTE/PATH/TO/A/TRUSTED/REPO": "trusted_repo",
}
GENERIC_TEMPLATE_REPLACEMENTS = {
    "<your-provider>": "...",
    "<your-default-model>": "...",
    "<your-default-profile>": "...",
}
PATH_PLACEHOLDER_RE = re.compile(r"/ABSOLUTE/PATH/TO/[A-Z0-9_./-]+")
TEMPLATE_PLACEHOLDER_RE = re.compile(r"<your-[^>]+>")
SKILL_NAME_RE = re.compile(r'/skills/([^/]+)/SKILL\.md"')
MCP_SECTION_RE = re.compile(r"^\[mcp_servers\.([^.]+)(?:\.[^\]]+)?\]$")
GENERATED_AGENT_FILE_HEADER = "# Generated by Codex bootstrap from shared agent markdown."
FRONTMATTER_RE = re.compile(r"^---\n(.*?)\n---\n?(.*)\Z", re.DOTALL)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate a local Codex config from the shared starter template."
    )
    parser.add_argument("--config-source", default=str(DEFAULT_CONFIG_SOURCE))
    parser.add_argument("--output")
    parser.add_argument("--repo-root")
    parser.add_argument("--codex-home")
    parser.add_argument("--workspace-parent")
    parser.add_argument("--m2-repository")
    parser.add_argument("--env-file")
    parser.add_argument("--enable-mcp", action="append", default=[])
    parser.add_argument("--generate-mcp-env", action="append", default=[])
    parser.add_argument("--home-dir")
    parser.add_argument("--log-directory")
    parser.add_argument("--trusted-repo")
    parser.add_argument("--model-provider")
    parser.add_argument("--model")
    parser.add_argument("--profile")
    parser.add_argument("--agents-mode", choices=AVAILABLE_AGENTS_MODES, default="copy")
    parser.add_argument("--agents-target")
    parser.add_argument("--disable-skill", action="append", default=[])
    parser.add_argument("--disable-mcp", action="append", default=[])
    parser.add_argument("--scan-path", action="append", default=[])
    parser.add_argument("--prompt", action="store_true")
    parser.add_argument("--undo", action="store_true")
    parser.add_argument("--allow-repo-write", action="store_true")
    parser.add_argument("--auth-shell", choices=AVAILABLE_AUTH_SHELLS)
    parser.add_argument("--auth-init-file")
    parser.add_argument("--bitbucket-auth-state", choices=AVAILABLE_AUTH_STATES)
    parser.add_argument("--bitbucket-base-url")
    parser.add_argument("--bitbucket-env-file")
    parser.add_argument("--jira-auth-state", choices=AVAILABLE_AUTH_STATES)
    parser.add_argument("--jira-base-url")
    parser.add_argument("--jira-oci-base-url")
    parser.add_argument("--generate-jira-oci-mcp-env", action="store_true")
    parser.add_argument("--sqlcl-team-config")
    parser.add_argument("--sqlcl-team-name")
    return parser.parse_args()


def resolve_path(raw_value: str | None, *, base_dir: Path | None = None) -> Path | None:
    if raw_value is None:
        return None
    candidate = Path(raw_value).expanduser()
    if not candidate.is_absolute():
        if base_dir is None:
            base_dir = Path.cwd()
        candidate = (base_dir / candidate).resolve()
    return candidate


def prompt_text(label: str, default: str | None = None, *, required: bool = False) -> str:
    suffix = f" [{default}]" if default not in (None, "") else ""
    while True:
        answer = input(f"{label}{suffix}: ").strip()
        if answer:
            return answer
        if default is not None:
            return default
        if not required:
            return ""
        print(f"{label} is required.", file=sys.stderr)


def prompt_yes_no(label: str, default: bool = True) -> bool:
    suffix = " [Y/n]" if default else " [y/N]"
    while True:
        answer = input(f"{label}{suffix}: ").strip().lower()
        if not answer:
            return default
        if answer in {"y", "yes"}:
            return True
        if answer in {"n", "no"}:
            return False
        print("Please answer yes or no.", file=sys.stderr)


def shell_quote(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')


def detect_auth_shell() -> str:
    shell_name = Path(os.environ.get("SHELL", "")).name.lower()
    if shell_name in AVAILABLE_AUTH_SHELLS:
        return shell_name
    return "zsh"


def default_auth_init_file(auth_shell: str) -> str:
    if auth_shell == "bash":
        return "~/.bashrc"
    return "~/.zshenv"


def auth_shell_name(args: argparse.Namespace) -> str:
    return args.auth_shell or detect_auth_shell()


def auth_init_file_display(args: argparse.Namespace) -> str:
    return args.auth_init_file or default_auth_init_file(auth_shell_name(args))


def split_blocks(text: str) -> list[str]:
    blocks: list[str] = []
    current: list[str] = []
    for line in text.splitlines(keepends=True):
        stripped = line.strip()
        is_header = stripped.startswith("[") and stripped.endswith("]")
        if is_header and current:
            blocks.append("".join(current))
            current = [line]
        else:
            current.append(line)
    if current:
        blocks.append("".join(current))
    return blocks


def block_header(block: str) -> str | None:
    for line in block.splitlines():
        stripped = line.strip()
        if stripped.startswith("[") and stripped.endswith("]"):
            return stripped
    return None


def filter_blocks(text: str, enabled_skills: set[str], enabled_mcp: set[str]) -> str:
    kept: list[str] = []
    for block in split_blocks(text):
        header = block_header(block)
        if header is None:
            kept.append(block)
            continue

        if header == "[[skills.config]]":
            match = SKILL_NAME_RE.search(block)
            if match and match.group(1) not in enabled_skills:
                continue
            kept.append(block)
            continue

        match = MCP_SECTION_RE.match(header)
        if match and match.group(1) in AVAILABLE_MCP_SERVERS and match.group(1) not in enabled_mcp:
            continue

        kept.append(block)
    return "".join(kept)


def replace_setting(text: str, key: str, value: str | None) -> str:
    pattern = re.compile(rf"(?m)^#?\s*{re.escape(key)}\s*=.*$")
    if not value:
        return text
    replacement = f'{key} = "{value}"'
    if pattern.search(text):
        return pattern.sub(replacement, text, count=1)
    return f"{replacement}\n{text}"


def replace_optional_root(text: str, placeholder: str, value: str | None) -> str:
    line_with_comma = f'  "{placeholder}",\n'
    line_without_comma = f'  "{placeholder}"\n'
    if value:
        return text.replace(placeholder, value)
    return text.replace(line_with_comma, "").replace(line_without_comma, "")


def replace_mcp_env_file_arg(text: str, server_name: str, env_file: str) -> str:
    header = f"[mcp_servers.{server_name}]"
    start = text.find(header)
    if start == -1:
        return text
    end = text.find("\n[", start + len(header))
    if end == -1:
        end = len(text)
    section = text[start:end]
    lines = section.splitlines(keepends=True)
    for index, line in enumerate(lines[:-1]):
        if line.strip() != '"--env-file",':
            continue
        newline = "\n" if lines[index + 1].endswith("\n") else ""
        indent = lines[index + 1][: len(lines[index + 1]) - len(lines[index + 1].lstrip())]
        lines[index + 1] = f'{indent}"{shell_quote(env_file)}",{newline}'
        return text[:start] + "".join(lines) + text[end:]
    return text


def scan_placeholders(text: str) -> tuple[list[str], list[str]]:
    path_hits = sorted(set(PATH_PLACEHOLDER_RE.findall(text)))
    generic_hits = sorted(set(TEMPLATE_PLACEHOLDER_RE.findall(text)))
    return path_hits, generic_hits


def format_path(path: Path) -> str:
    return str(path.expanduser().resolve())


def resolve_shared_mcp_env_file(args: argparse.Namespace) -> Path | None:
    return resolve_path(args.env_file)


def resolve_mcp_env_file(args: argparse.Namespace, server_name: str) -> Path | None:
    if server_name not in MCP_ENV_SERVER_NAMES:
        return None
    return resolve_shared_mcp_env_file(args)


def default_mcp_env_path(codex_home: str | None, server_name: str) -> str:
    base_home = resolve_path(codex_home) or (Path.home() / ".codex")
    return str(base_home / DEFAULT_MCP_ENV_FILENAMES[server_name])


def resolve_bitbucket_env_file(args: argparse.Namespace) -> Path:
    codex_home = resolve_path(args.codex_home) or (Path.home() / ".codex")
    return resolve_path(args.bitbucket_env_file) or (codex_home / DEFAULT_BITBUCKET_ENV_FILENAME)


def resolve_home_dir(args: argparse.Namespace) -> Path:
    return resolve_path(args.home_dir) or Path.home()


def resolve_jira_sd_mcp_env_file(args: argparse.Namespace) -> Path:
    return resolve_home_dir(args) / DEFAULT_JIRA_SD_MCP_ENV_FILENAME


def resolve_jira_oci_mcp_env_file(args: argparse.Namespace) -> Path:
    return resolve_home_dir(args) / DEFAULT_JIRA_OCI_MCP_ENV_FILENAME


def env_values_present(env_names: tuple[str, ...]) -> bool:
    return all((os.environ.get(env_name) or "").strip() for env_name in env_names)


def env_any_pair_present(env_pairs: tuple[tuple[str, str], ...]) -> bool:
    return any(env_values_present(env_pair) for env_pair in env_pairs)


def read_exported_env_file(path: Path) -> dict[str, str]:
    if not path.exists() or path.is_dir():
        return {}
    values: dict[str, str] = {}
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        stripped = raw_line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        if stripped.startswith("export "):
            stripped = stripped[len("export ") :].strip()
        if "=" not in stripped:
            continue
        key, value = stripped.split("=", 1)
        key = key.strip()
        value = value.strip()
        if len(value) >= 2 and value[0] == value[-1] and value[0] in {'"', "'"}:
            value = value[1:-1]
        values[key] = value
    return values


def env_file_values_present(path: Path, env_names: tuple[str, ...]) -> bool:
    values = read_exported_env_file(path)
    return all((values.get(env_name) or "").strip() for env_name in env_names)


def env_file_any_pair_present(path: Path, env_pairs: tuple[tuple[str, str], ...]) -> bool:
    values = read_exported_env_file(path)
    return any(all((values.get(env_name) or "").strip() for env_name in env_pair) for env_pair in env_pairs)


def list_sqlcl_team_names(config_path: Path) -> list[str]:
    raw_config = tomllib.loads(config_path.read_text(encoding="utf-8"))
    team_entries = raw_config.get("team")
    if not isinstance(team_entries, list):
        return []
    names: list[str] = []
    for team_entry in team_entries:
        if not isinstance(team_entry, dict):
            continue
        sqlcl_config = team_entry.get("sqlcl")
        team_name = team_entry.get("name")
        if isinstance(sqlcl_config, dict) and isinstance(team_name, str) and team_name.strip():
            names.append(team_name.strip())
    return names


def load_sqlcl_team_connection_config(config_path: Path, team_name: str | None = None) -> dict[str, str]:
    raw_config = tomllib.loads(config_path.read_text(encoding="utf-8"))
    team_entries = raw_config.get("team")
    if not isinstance(team_entries, list):
        raise ValueError(f"Team config must contain one or more [[team]] blocks: {config_path}")

    candidates: list[dict[str, str]] = []
    for team_entry in team_entries:
        if not isinstance(team_entry, dict):
            continue
        raw_team_name = team_entry.get("name")
        sqlcl_config = team_entry.get("sqlcl")
        if not isinstance(raw_team_name, str) or not raw_team_name.strip() or not isinstance(sqlcl_config, dict):
            continue
        candidate = {
            "team_name": raw_team_name.strip(),
            "connection_name": str(sqlcl_config.get("connection_name", "")).strip(),
            "connect_string": str(sqlcl_config.get("connect_string", "")).strip(),
            "username": str(sqlcl_config.get("username", "")).strip(),
            "password_env_var": str(sqlcl_config.get("password_env_var", "")).strip(),
            "password_env_file": str(
                sqlcl_config.get("password_env_file", DEFAULT_SQLCL_PASSWORD_ENV_FILE)
            ).strip()
            or DEFAULT_SQLCL_PASSWORD_ENV_FILE,
            "tunnel_command": str(sqlcl_config.get("tunnel_command", "")).strip(),
            "notes": str(sqlcl_config.get("notes", "")).strip(),
        }
        candidates.append(candidate)

    if team_name:
        filtered = [candidate for candidate in candidates if candidate["team_name"] == team_name]
    else:
        filtered = candidates

    if not filtered:
        available = ", ".join(candidate["team_name"] for candidate in candidates) or "(none)"
        target = f" for team {team_name}" if team_name else ""
        raise ValueError(
            f"No [team.sqlcl] block found in {config_path}{target}. Available teams: {available}"
        )
    if len(filtered) > 1:
        names = ", ".join(candidate["team_name"] for candidate in filtered)
        raise ValueError(
            f"Multiple [team.sqlcl] blocks found in {config_path}. Use --sqlcl-team-name to choose one of: {names}"
        )

    selected = filtered[0]
    if not selected["connection_name"]:
        raise ValueError(
            f"Missing required team.sqlcl field in {config_path} for {selected['team_name']}: "
            "connection_name"
        )
    bootstrap_keys = ("connect_string", "username", "password_env_var")
    bootstrap_values_present = [key for key in bootstrap_keys if selected[key]]
    if bootstrap_values_present:
        missing = [key for key in bootstrap_keys if not selected[key]]
        if missing:
            raise ValueError(
                f"Incomplete team.sqlcl bootstrap fields in {config_path} for {selected['team_name']}: "
                + ", ".join(missing)
                + ". Define either only connection_name to use an existing saved SQLcl connection, "
                + "or define connection_name plus connect_string, username, and password_env_var "
                + "to let bootstrap create or refresh it."
            )
        selected["setup_mode"] = "bootstrap"
    else:
        selected["setup_mode"] = "existing"
    return selected


def resolve_sqlcl_password(
    sqlcl_config: dict[str, str],
    *,
    team_config_path: Path,
) -> tuple[str, Path]:
    password_env_var = sqlcl_config["password_env_var"]
    env_file_path = (
        resolve_path(sqlcl_config.get("password_env_file"), base_dir=team_config_path.parent)
        or (Path.home() / ".env")
    )
    password = (os.environ.get(password_env_var) or "").strip()
    if password:
        return password, env_file_path

    env_file_values = read_exported_env_file(env_file_path)
    password = (env_file_values.get(password_env_var) or "").strip()
    if password:
        return password, env_file_path

    if env_file_path.exists():
        raise ValueError(
            f"SQLcl password env var {password_env_var} was not found in the current environment "
            f"or in {env_file_path}"
        )
    raise ValueError(
        f"SQLcl password env var {password_env_var} was not found in the current environment, "
        f"and the configured env file does not exist: {env_file_path}"
    )


def sqlcl_literal(value: str) -> str:
    if "\n" in value or "\r" in value:
        raise ValueError("SQLcl values cannot contain newlines.")
    return '"' + value.replace('"', '""') + '"'


def compact_process_output(stdout: str, stderr: str) -> str:
    lines = [line.strip() for line in (stdout + "\n" + stderr).splitlines() if line.strip()]
    if not lines:
        return ""
    return "\n".join(lines[-10:])


def render_sqlcl_connection_setup_script(sqlcl_config: dict[str, str], password: str) -> str:
    connection_name = sqlcl_literal(sqlcl_config["connection_name"])
    username = sqlcl_literal(sqlcl_config["username"])
    connect_string = sqlcl_literal(sqlcl_config["connect_string"])
    password_literal = sqlcl_literal(password)
    return "\n".join(
        [
            "whenever oserror exit failure rollback",
            f"connmgr delete -conn {connection_name}",
            "whenever sqlerror exit failure rollback",
            (
                f"connect -save {connection_name} -savepwd "
                f"-user {username} -password {password_literal} -url {connect_string}"
            ),
            f"connmgr show {connection_name}",
            "exit",
            "",
        ]
    )


def configure_sqlcl_saved_connection(
    args: argparse.Namespace,
    values: dict[str, str],
) -> tuple[str, list[str]] | None:
    if not args.sqlcl_team_config:
        return None

    team_config_path = resolve_path(args.sqlcl_team_config)
    if team_config_path is None or not team_config_path.exists():
        raise ValueError(f"SQLcl team config does not exist: {args.sqlcl_team_config}")

    sqlcl_config = load_sqlcl_team_connection_config(team_config_path, args.sqlcl_team_name)
    if sqlcl_config["setup_mode"] == "existing":
        notes = [
            "Using existing SQLcl saved connection for "
            f"{sqlcl_config['team_name']}: {sqlcl_config['connection_name']}",
        ]
        if sqlcl_config.get("tunnel_command"):
            notes.append(f"SQLcl tunnel helper: {sqlcl_config['tunnel_command']}")
        if sqlcl_config.get("notes"):
            notes.append(f"SQLcl notes: {sqlcl_config['notes']}")
        return notes[0], notes[1:]

    password, env_file_path = resolve_sqlcl_password(sqlcl_config, team_config_path=team_config_path)

    sqlcl_binary = Path(values["home_dir"]) / "Downloads" / "sqlcl" / "bin" / "sql"
    if not sqlcl_binary.exists():
        raise ValueError(
            "SQLcl team-config setup requires the SQLcl binary at "
            f"{sqlcl_binary}. Install SQLcl there or update the generated command path first."
        )

    setup_script = render_sqlcl_connection_setup_script(sqlcl_config, password)
    try:
        result = subprocess.run(
            [str(sqlcl_binary), "-S", "/nolog"],
            input=setup_script,
            text=True,
            capture_output=True,
            check=False,
        )
    except OSError as exc:
        raise RuntimeError(f"Failed to launch SQLcl from {sqlcl_binary}: {exc}") from exc

    if result.returncode != 0:
        detail = compact_process_output(result.stdout, result.stderr)
        message_lines = [
            "Failed to configure the saved SQLcl connection "
            f"{sqlcl_config['connection_name']} for team {sqlcl_config['team_name']}.",
            f"Bootstrap read {sqlcl_config['password_env_var']} from {env_file_path}.",
        ]
        if sqlcl_config.get("tunnel_command"):
            message_lines.append(
                "If the local listener is not ready yet, run this prerequisite first: "
                f"{sqlcl_config['tunnel_command']}"
            )
        if detail:
            message_lines.append(detail)
        raise RuntimeError("\n".join(message_lines))

    notes = [
        f"SQLcl saved connection configured for {sqlcl_config['team_name']}: {sqlcl_config['connection_name']}",
        (
            "SQLcl password source: "
            f"{sqlcl_config['password_env_var']} from {env_file_path}"
        ),
    ]
    if sqlcl_config.get("tunnel_command"):
        notes.append(f"SQLcl tunnel helper: {sqlcl_config['tunnel_command']}")
    if sqlcl_config.get("notes"):
        notes.append(f"SQLcl notes: {sqlcl_config['notes']}")
    return notes[0], notes[1:]


def bitbucket_auth_is_configured(args: argparse.Namespace) -> bool:
    env_names = ("BASE_URL", "BITBUCKET_TOKEN")
    if env_values_present(env_names):
        return True
    return env_file_values_present(resolve_bitbucket_env_file(args), env_names)


def jira_auth_is_configured(args: argparse.Namespace) -> bool:
    sd_ready = env_file_values_present(resolve_jira_sd_mcp_env_file(args), JIRA_MCP_AUTH_ENV_NAMES)
    oci_ready = env_file_values_present(resolve_jira_oci_mcp_env_file(args), JIRA_MCP_AUTH_ENV_NAMES)
    return sd_ready and oci_ready


def dedupe_names(values: list[str]) -> list[str]:
    seen: set[str] = set()
    ordered: list[str] = []
    for value in values:
        if value in seen:
            continue
        seen.add(value)
        ordered.append(value)
    return ordered


def resolve_enabled_mcp(args: argparse.Namespace) -> set[str]:
    enabled = set(DEFAULT_ENABLED_MCP_SERVERS)
    enabled.update(args.enable_mcp or [])
    enabled.difference_update(args.disable_mcp or [])
    return {name for name in AVAILABLE_MCP_SERVERS if name in enabled}


def build_values(args: argparse.Namespace) -> dict[str, str]:
    repo_root = resolve_path(args.repo_root) or REPO_ROOT
    codex_home = resolve_path(args.codex_home) or (Path.home() / ".codex")
    home_root = Path.home()
    workspace_parent = resolve_path(args.workspace_parent) or repo_root.parent
    output = resolve_path(args.output) or (codex_home / "config.toml")
    m2_repository = resolve_path(args.m2_repository)
    home_dir = resolve_path(args.home_dir) or home_root
    log_directory = resolve_path(args.log_directory)
    trusted_repo = resolve_path(args.trusted_repo) or repo_root

    enabled_skills = {
        skill for skill in AVAILABLE_SKILLS if skill not in set(args.disable_skill or [])
    }
    enabled_mcp = resolve_enabled_mcp(args)

    stlm_mcp_env_file = resolve_mcp_env_file(args, "stlm-mcp")
    mcp_dope_env_file = resolve_mcp_env_file(args, "mcp-dope")
    return {
        "repo_root": format_path(repo_root),
        "codex_home": format_path(codex_home),
        "workspace_parent": format_path(workspace_parent),
        "output": format_path(output),
        "m2_repository": format_path(m2_repository) if m2_repository else "",
        "uv_cache": format_path(home_root / ".cache" / "uv"),
        "chromium_support_dir": format_path(
            home_root / "Library" / "Application Support" / "Chromium"
        ),
        "chrome_support_dir": format_path(
            home_root / "Library" / "Application Support" / "Google" / "Chrome"
        ),
        "stlm_mcp_env_file": format_path(stlm_mcp_env_file) if stlm_mcp_env_file else "",
        "mcp_dope_env_file": format_path(mcp_dope_env_file) if mcp_dope_env_file else "",
        "home_dir": format_path(home_dir),
        "log_directory": format_path(log_directory) if log_directory else "",
        "trusted_repo": format_path(trusted_repo),
        "model_provider": args.model_provider or "",
        "model": args.model or "",
        "profile": args.profile or "",
        "enabled_skills": ",".join(sorted(enabled_skills)),
        "enabled_mcp": ",".join(sorted(enabled_mcp)),
    }


def missing_required_mcp_inputs(args: argparse.Namespace, enabled_mcp: set[str]) -> list[str]:
    missing: list[str] = []
    env_enabled = [server_name for server_name in MCP_ENV_SERVER_NAMES if server_name in enabled_mcp]
    if env_enabled and not resolve_shared_mcp_env_file(args):
        missing.append("--env-file")
    if any(server_name in enabled_mcp for server_name in MCP_SERVERS_REQUIRING_LOG_DIRECTORY) and not args.log_directory:
        missing.append("--log-directory")
    return missing


def prompt_for_missing(args: argparse.Namespace) -> argparse.Namespace:
    detected_repo_root = str(REPO_ROOT)
    default_codex_home = str(Path.home() / ".codex")
    if args.codex_home:
        default_home = args.codex_home
    elif prompt_yes_no(f"Use default Codex home {default_codex_home}?", default=True):
        default_home = default_codex_home
    else:
        default_home = None
    args.codex_home = prompt_text("Codex home", default_home, required=True)
    args.output = prompt_text(
        "Output config path",
        args.output or str(Path(args.codex_home).expanduser() / "config.toml"),
        required=True,
    )
    if args.undo:
        args.agents_target = prompt_text(
            "Global AGENTS.md target",
            args.agents_target or str(Path(args.codex_home).expanduser() / "AGENTS.md"),
            required=True,
        )
        return args

    args.repo_root = prompt_text("Shared repo root", args.repo_root or detected_repo_root, required=True)
    args.workspace_parent = prompt_text(
        "Workspace parent",
        args.workspace_parent or str(Path(args.repo_root).expanduser().resolve().parent),
        required=True,
    )
    if not args.m2_repository and prompt_yes_no(
        "Add the local Maven repository to writable roots for sandboxed builds?", default=False
    ):
        args.m2_repository = prompt_text(
            "Local Maven repository",
            DEFAULT_M2_REPOSITORY,
            required=True,
        )
    if not any((args.model_provider, args.model, args.profile)) and prompt_yes_no(
        "Override the shared Enterprise ChatGPT model defaults?", default=False
    ):
        args.model_provider = prompt_text("Model provider (optional)", args.model_provider or SHARED_MODEL_PROVIDER)
        args.model = prompt_text("Default model", args.model or SHARED_MODEL)
        args.profile = prompt_text("Profile (optional)", args.profile or SHARED_PROFILE)
    args.trusted_repo = prompt_text(
        "Trusted repo example path",
        args.trusted_repo or args.repo_root,
        required=True,
    )
    if prompt_yes_no("Install global AGENTS.md into Codex home?", default=args.agents_mode != "skip"):
        if args.agents_mode not in {"symlink", "copy"}:
            args.agents_mode = "copy"
        args.agents_target = prompt_text(
            "Global AGENTS.md target",
            args.agents_target or str(Path(args.codex_home).expanduser() / "AGENTS.md"),
            required=True,
        )
    else:
        args.agents_mode = "skip"
        args.agents_target = args.agents_target or str(Path(args.codex_home).expanduser() / "AGENTS.md")

    disabled_skills: list[str] = []
    for skill_name in AVAILABLE_SKILLS:
        if not prompt_yes_no(f"Enable skill {skill_name}?", default=skill_name not in set(args.disable_skill)):
            disabled_skills.append(skill_name)
    args.disable_skill = disabled_skills

    enabled_skills = [name for name in AVAILABLE_SKILLS if name not in set(disabled_skills)]
    if "bitbucket-pr" in enabled_skills:
        args.auth_shell = prompt_text(
            "Shell for Bitbucket auth helper (zsh or bash)",
            args.auth_shell or detect_auth_shell(),
            required=True,
        ).strip().lower()
        while args.auth_shell not in AVAILABLE_AUTH_SHELLS:
            print("Shell must be either zsh or bash.", file=sys.stderr)
            args.auth_shell = prompt_text(
                "Shell for Bitbucket auth helper (zsh or bash)",
                detect_auth_shell(),
                required=True,
            ).strip().lower()
        args.auth_init_file = prompt_text(
            "Shell init file for Bitbucket auth helper",
            args.auth_init_file or default_auth_init_file(args.auth_shell),
            required=True,
        )
    if "bitbucket-pr" in enabled_skills:
        if args.bitbucket_auth_state not in AVAILABLE_AUTH_STATES:
            ready = prompt_yes_no(
                "Is Bitbucket PR auth already set up (BASE_URL + BITBUCKET_TOKEN)?",
                default=bitbucket_auth_is_configured(args),
            )
            args.bitbucket_auth_state = "ready" if ready else "needs-setup"
        if args.bitbucket_auth_state == "ready" and not env_values_present(("BASE_URL", "BITBUCKET_TOKEN")):
            args.bitbucket_env_file = prompt_text(
                "Existing Bitbucket env helper path",
                args.bitbucket_env_file or str(resolve_bitbucket_env_file(args)),
                required=True,
            )
        if args.bitbucket_auth_state == "needs-setup":
            args.bitbucket_base_url = prompt_text(
                "Bitbucket base URL",
                args.bitbucket_base_url or DEFAULT_BITBUCKET_BASE_URL,
                required=True,
            )
            args.bitbucket_env_file = prompt_text(
                "Bitbucket env helper path",
                args.bitbucket_env_file
                or str(Path(args.codex_home).expanduser() / DEFAULT_BITBUCKET_ENV_FILENAME),
                required=True,
            )
    else:
        args.bitbucket_auth_state = None
    if "jira-ticket" in enabled_skills:
        if args.jira_auth_state not in AVAILABLE_AUTH_STATES:
            ready = prompt_yes_no(
                "Are Jira MCP env files already set up for Jira-SD and Jira OCI?",
                default=jira_auth_is_configured(args),
            )
            args.jira_auth_state = "ready" if ready else "needs-setup"
        if args.jira_auth_state == "ready" and not jira_auth_is_configured(args):
            print(
                "Jira auth expects JIRA_URL and JIRA_PERSONAL_TOKEN in "
                f"{resolve_jira_sd_mcp_env_file(args)} and {resolve_jira_oci_mcp_env_file(args)}.",
                file=sys.stderr,
            )
        if args.jira_auth_state == "needs-setup":
            args.jira_oci_base_url = prompt_text(
                "Jira OCI base URL",
                args.jira_oci_base_url or DEFAULT_JIRA_OCI_BASE_URL,
                required=True,
            )
            args.generate_jira_oci_mcp_env = prompt_yes_no(
                f"Generate Jira OCI MCP env helper at {resolve_jira_oci_mcp_env_file(args)}?",
                default=True,
            )
    else:
        args.jira_auth_state = None

    disabled_mcp: list[str] = []
    enabled_optional_mcp: list[str] = []
    current_enabled_mcp = resolve_enabled_mcp(args)
    for server_name in AVAILABLE_MCP_SERVERS:
        if not prompt_yes_no(
            f"Enable MCP server {server_name}?", default=server_name in current_enabled_mcp
        ):
            disabled_mcp.append(server_name)
        elif server_name not in DEFAULT_ENABLED_MCP_SERVERS:
            enabled_optional_mcp.append(server_name)
    args.disable_mcp = disabled_mcp
    args.enable_mcp = enabled_optional_mcp

    enabled_mcp = [name for name in AVAILABLE_MCP_SERVERS if name in resolve_enabled_mcp(args)]
    args.generate_mcp_env = dedupe_names(list(args.generate_mcp_env or []))
    env_enabled_mcp = [name for name in enabled_mcp if name in MCP_ENV_SERVER_NAMES]
    if env_enabled_mcp:
        default_path = (
            args.env_file
            or default_mcp_env_path(args.codex_home, env_enabled_mcp[0])
        )
        current_path = resolve_path(default_path)
        server_label = ", ".join(env_enabled_mcp)
        has_existing_env = prompt_yes_no(
            f"Do you already have one shared .env file for {server_label}?",
            default=bool(current_path and current_path.exists()),
        )
        path_label = (
            f"Existing shared .env file for {server_label}"
            if has_existing_env
            else f"Desired shared .env file path for {server_label}"
        )
        args.env_file = prompt_text(path_label, default_path, required=True)
        if not has_existing_env:
            env_path = resolve_path(args.env_file)
            if env_path and env_path.exists():
                if prompt_yes_no(
                    f"{env_path} already exists. Replace it with a generated starter .env file for {server_label}?",
                    default=False,
                ):
                    args.generate_mcp_env.extend(env_enabled_mcp)
            elif prompt_yes_no(
                f"Generate a starter .env file for {server_label} at {env_path}?",
                default=True,
            ):
                args.generate_mcp_env.extend(env_enabled_mcp)
    shared_home_mcp = [name for name in enabled_mcp if name in MCP_SERVERS_USING_SHARED_HOME]
    if shared_home_mcp:
        args.home_dir = prompt_text(
            "HOME for enabled MCP servers",
            args.home_dir or str(Path.home()),
            required=True,
        )
    if env_enabled_mcp:
        args.log_directory = prompt_text(
            "Log directory for enabled MCP servers",
            args.log_directory or str(Path(args.codex_home).expanduser() / "log"),
            required=True,
        )
    if "sqlcl" in enabled_mcp and prompt_yes_no(
        "Use SQLcl connection metadata from an On-Call Investigation team config?",
        default=bool(args.sqlcl_team_config),
    ):
        args.sqlcl_team_config = prompt_text(
            "On-Call Investigation team config path",
            args.sqlcl_team_config or "",
            required=True,
        )
        team_config_path = resolve_path(args.sqlcl_team_config)
        if team_config_path and team_config_path.exists():
            sqlcl_team_names = list_sqlcl_team_names(team_config_path)
            if len(sqlcl_team_names) == 1:
                args.sqlcl_team_name = sqlcl_team_names[0]
            elif len(sqlcl_team_names) > 1:
                args.sqlcl_team_name = prompt_text(
                    "Team name for SQLcl connection setup",
                    args.sqlcl_team_name or sqlcl_team_names[0],
                    required=True,
                )
    else:
        args.sqlcl_team_config = None
        args.sqlcl_team_name = None
    return args


def backup_existing_file(path: Path) -> Path | None:
    if not path.exists():
        return None
    timestamp = datetime.now().strftime("%Y%m%d%H%M%S")
    backup_path = path.with_name(f"{path.name}.bak.{timestamp}")
    shutil.copy2(path, backup_path)
    return backup_path


def backup_existing_path(path: Path) -> Path | None:
    if not path.exists() and not path.is_symlink():
        return None
    timestamp = datetime.now().strftime("%Y%m%d%H%M%S")
    backup_path = path.with_name(f"{path.name}.bak.{timestamp}")
    if path.is_symlink() or path.is_file():
        shutil.copy2(path, backup_path, follow_symlinks=False)
    elif path.is_dir():
        shutil.copytree(path, backup_path, symlinks=True)
    return backup_path


def replace_existing_path(path: Path) -> Path | None:
    if not path.exists() and not path.is_symlink():
        return None
    backup_path = backup_existing_path(path)
    if path.is_symlink() or path.is_file():
        path.unlink()
    elif path.is_dir():
        shutil.rmtree(path)
    return backup_path


def replace_existing_skill_path(path: Path, backups_dir: Path) -> Path | None:
    if not path.exists() and not path.is_symlink():
        return None
    backups_dir.mkdir(parents=True, exist_ok=True)
    timestamp = datetime.now().strftime("%Y%m%d%H%M%S")
    backup_path = backups_dir / f"{path.name}.bak.{timestamp}"
    if path.is_symlink() or path.is_file():
        shutil.copy2(path, backup_path, follow_symlinks=False)
        path.unlink()
    elif path.is_dir():
        shutil.copytree(path, backup_path, symlinks=True)
        shutil.rmtree(path)
    return backup_path


def render_agents_content(source: Path, repo_root: Path) -> str:
    rendered = source.read_text(encoding="utf-8")
    for relative_path in AGENTS_RELATIVE_PATHS:
        absolute_path = format_path(repo_root / relative_path)
        rendered = rendered.replace(f"`{relative_path}`", f"`{absolute_path}`")
        rendered = rendered.replace(f"({relative_path})", f"({absolute_path})")
        rendered = rendered.replace(f": `{relative_path}`", f": `{absolute_path}`")
        rendered = rendered.replace(f"- `{relative_path}`", f"- `{absolute_path}`")
    return rendered


def install_agents_entrypoint(source: Path, target: Path, mode: str, repo_root: Path) -> tuple[str, Path | None]:
    if mode == "skip":
        return "Skipped global AGENTS.md installation.", None

    target.parent.mkdir(parents=True, exist_ok=True)
    backup_path = replace_existing_path(target)
    rendered_content = render_agents_content(source, repo_root)
    target.write_text(rendered_content, encoding="utf-8")
    if mode == "symlink":
        return (
            f"Installed rendered global AGENTS.md copy at {target} "
            f"(symlink mode is converted to a local rendered file so repo-relative routing works).",
            backup_path,
        )
    return f"Installed rendered global AGENTS.md copy: {target}", backup_path


def parse_scalar(value: str) -> str:
    parsed = value.strip()
    if len(parsed) >= 2 and parsed[0] == parsed[-1] and parsed[0] in {'"', "'"}:
        return parsed[1:-1]
    return parsed


def parse_agent_markdown(source: Path) -> dict[str, str]:
    text = source.read_text(encoding="utf-8")
    match = FRONTMATTER_RE.match(text)
    if match:
        frontmatter, body = match.groups()
    else:
        frontmatter, body = "", text

    name = source.stem
    description = ""
    model = ""
    reasoning = ""
    in_harness = False
    in_codex = False
    for line in frontmatter.splitlines():
        stripped = line.strip()
        if not stripped:
            continue
        if line.startswith("    ") and in_harness and in_codex:
            if stripped.startswith("model:"):
                model = parse_scalar(stripped.split(":", 1)[1])
            elif stripped.startswith("model_reasoning_effort:"):
                reasoning = parse_scalar(stripped.split(":", 1)[1])
            continue
        if line.startswith("  ") and in_harness:
            in_codex = stripped == "codex:"
            continue
        in_harness = False
        in_codex = False
        if stripped.startswith("name:"):
            name = parse_scalar(stripped.split(":", 1)[1])
        elif stripped.startswith("description:"):
            description = parse_scalar(stripped.split(":", 1)[1])
        elif stripped == "harness:":
            in_harness = True

    return {
        "name": name,
        "description": description,
        "developer_instructions": body.strip(),
        "model": model,
        "model_reasoning_effort": reasoning,
    }


def render_agent_config(agent_definition: dict[str, str]) -> str:
    lines = [GENERATED_AGENT_FILE_HEADER]
    lines.append(f'description = {json.dumps(agent_definition["description"])}')
    lines.append(f'developer_instructions = {json.dumps(agent_definition["developer_instructions"])}')
    if agent_definition["model"]:
        lines.append(f'model = {json.dumps(agent_definition["model"])}')
    if agent_definition["model_reasoning_effort"]:
        lines.append(
            f'model_reasoning_effort = {json.dumps(agent_definition["model_reasoning_effort"])}'
        )
    lines.append(f'name = {json.dumps(agent_definition["name"])}')
    return "\n".join(lines) + "\n"


def is_generated_agent_file(path: Path) -> bool:
    if not path.exists() or path.is_dir():
        return False
    first_line = path.read_text(encoding="utf-8").splitlines()[:1]
    return bool(first_line) and first_line[0] == GENERATED_AGENT_FILE_HEADER


def write_generated_agent_files(repo_root: Path, codex_home: Path) -> list[tuple[str, Path, Path | None]]:
    agents_dir = codex_home / "agents"
    agents_dir.mkdir(parents=True, exist_ok=True)

    agent_definitions = [
        parse_agent_markdown(source)
        for source in sorted((repo_root / "agents").glob("*.md"))
        if source.is_file()
    ]
    written: list[tuple[str, Path, Path | None]] = []
    expected_paths: set[Path] = set()
    for agent_definition in agent_definitions:
        destination = agents_dir / f'{agent_definition["name"]}.toml'
        expected_paths.add(destination)
        backup_path = write_helper_file(destination, render_agent_config(agent_definition))
        written.append((agent_definition["name"], destination, backup_path))

    for existing in sorted(agents_dir.glob("*.toml")):
        if existing in expected_paths or not is_generated_agent_file(existing):
            continue
        existing.unlink()

    return written


def install_skill_links(
    repo_root: Path,
    codex_home: Path,
    enabled_skills: set[str],
) -> list[tuple[str, Path, str]]:
    skills_dir = codex_home / "skills"
    skill_backups_dir = codex_home / "skill-backups"
    skills_dir.mkdir(parents=True, exist_ok=True)

    results: list[tuple[str, Path, str]] = []
    for skill_name in sorted(enabled_skills):
        source = repo_root / "skills" / skill_name
        destination = skills_dir / skill_name
        if not (source / "SKILL.md").exists():
            results.append((skill_name, destination, f"missing source: {source}"))
            continue
        if destination.is_symlink():
            current_target = destination.resolve()
            if current_target == source.resolve():
                results.append((skill_name, destination, "already linked"))
                continue
            backup_path = replace_existing_skill_path(destination, skill_backups_dir)
            destination.symlink_to(source, target_is_directory=True)
            results.append((skill_name, destination, f"relinked; backup at {backup_path}"))
            continue
        if destination.exists():
            backup_path = replace_existing_skill_path(destination, skill_backups_dir)
            destination.symlink_to(source, target_is_directory=True)
            results.append((skill_name, destination, f"linked; backup at {backup_path}"))
            continue
        destination.symlink_to(source, target_is_directory=True)
        results.append((skill_name, destination, "linked"))
    return results


def write_helper_file(path: Path, content: str, *, executable: bool = False) -> Path | None:
    path.parent.mkdir(parents=True, exist_ok=True)
    backup_path = backup_existing_file(path)
    path.write_text(content, encoding="utf-8")
    if executable:
        path.chmod(0o755)
    return backup_path


def render_bitbucket_env_file(base_url: str) -> str:
    quoted_base_url = shell_quote(base_url)
    return (
        "# Generated by Codex bootstrap to help with the bitbucket-pr skill.\n"
        "# Fill BITBUCKET_TOKEN before sourcing this file.\n"
        f'export BASE_URL="{quoted_base_url}"\n'
        'export BITBUCKET_TOKEN=""\n'
    )


def render_jira_oci_mcp_env_file(oci_base_url: str) -> str:
    quoted_oci_base_url = shell_quote(oci_base_url)
    return (
        f"{GENERATED_JIRA_OCI_MCP_ENV_HEADER}\n"
        "# Used by mcp-atlassian-jira-oci and by jira_ticket_api.py --jira-instance oci.\n"
        "# Fill JIRA_PERSONAL_TOKEN before using live Jira OCI calls.\n"
        f'JIRA_URL="{quoted_oci_base_url}"\n'
        'JIRA_PERSONAL_TOKEN=""\n'
        'JIRA_SSL_VERIFY="true"\n'
    )


def print_auth_shell_guidance(
    args: argparse.Namespace,
    bitbucket_env_path: Path | None,
    jira_env_path: Path | None,
) -> None:
    source_lines: list[str] = []
    if bitbucket_env_path is not None:
        source_lines.append(f'source "{bitbucket_env_path}"')
    if jira_env_path is not None:
        source_lines.append(f'source "{jira_env_path}"')
    if not source_lines:
        return

    shell_name = auth_shell_name(args)
    init_file = auth_init_file_display(args)
    print(f"Configure {init_file} so every {shell_name} session loads the shell auth helpers:")
    for source_line in source_lines:
        print(source_line)


def zshenv_guidance_path(path: Path, raw_value: str | None, auth_state: str | None) -> Path | None:
    if path.exists() or raw_value or auth_state == "needs-setup":
        return path
    return None


def print_generated_auth_helpers(
    auth_helper_results: list[tuple[str, Path, Path | None]],
    *,
    include_fill_guidance: bool,
) -> None:
    for helper_label, helper_path, helper_backup in auth_helper_results:
        print(f"{helper_label}: {helper_path}")
        if helper_backup:
            print(f"{helper_label} backup created: {helper_backup}")
        if include_fill_guidance:
            if helper_label == "Bitbucket PR env helper":
                print("Fill BITBUCKET_TOKEN in that file.")
            elif helper_label == "Jira OCI MCP env helper":
                print("Fill JIRA_PERSONAL_TOKEN in that file.")


def render_mcp_env_section(server_name: str, repo_root: Path, home_dir: Path) -> str:
    if server_name in MCP_ENV_TEMPLATE_FILENAMES:
        template_path = TEMPLATES_DIR / MCP_ENV_TEMPLATE_FILENAMES[server_name]
        rendered = template_path.read_text(encoding="utf-8").rstrip()
        rendered = rendered.replace("/ABSOLUTE/PATH/TO/THIS/REPO", format_path(repo_root))
        return rendered.replace("/ABSOLUTE/PATH/TO/YOUR/HOME", format_path(home_dir))
    raise ValueError(f"Unsupported MCP env helper generation target: {server_name}")


def render_mcp_env_file(server_names: list[str], repo_root: Path, home_dir: Path) -> str:
    if not any(name in MCP_ENV_GENERATOR_NAMES for name in server_names):
        return ""
    return render_mcp_env_section("mcp-dope", repo_root, home_dir) + "\n"


def is_generated_mcp_env_file(path: Path) -> bool:
    if not path.exists() or path.is_dir():
        return False
    first_line = path.read_text(encoding="utf-8").splitlines()[:1]
    return bool(first_line) and first_line[0].startswith("# Generated by Codex bootstrap for ")


def write_generated_mcp_env_files(
    args: argparse.Namespace,
    enabled_mcp: set[str],
    repo_root: Path,
) -> list[tuple[str, Path, Path | None]]:
    grouped_paths: dict[Path, list[str]] = {}
    for server_name in dedupe_names(list(args.generate_mcp_env or [])):
        if server_name not in enabled_mcp:
            continue
        env_path = resolve_mcp_env_file(args, server_name)
        if env_path is None:
            continue
        grouped_paths.setdefault(env_path, []).append(server_name)

    results: list[tuple[str, Path, Path | None]] = []
    home_dir = resolve_path(args.home_dir) or Path.home()
    for env_path, server_names in grouped_paths.items():
        backup_path = write_helper_file(env_path, render_mcp_env_file(server_names, repo_root, home_dir))
        results.append((", ".join(server_names), env_path, backup_path))
    return results


def remove_bootstrap_output(path: Path, label: str) -> str:
    if not path.exists() and not path.is_symlink():
        return f"No {label} found at {path}"
    if path.is_dir() and not path.is_symlink():
        return f"Skipped {label} because {path} is a directory"
    path.unlink()
    return f"Removed {label}: {path}"


def is_generated_jira_oci_mcp_env_file(path: Path) -> bool:
    if not path.exists() or path.is_dir():
        return False
    try:
        first_line = path.read_text(encoding="utf-8").splitlines()[0]
    except (IndexError, OSError, UnicodeDecodeError):
        return False
    return first_line.strip() == GENERATED_JIRA_OCI_MCP_ENV_HEADER


def undo_bootstrap(args: argparse.Namespace) -> int:
    codex_home = resolve_path(args.codex_home) or (Path.home() / ".codex")
    repo_root = resolve_path(args.repo_root) or REPO_ROOT
    output_path = resolve_path(args.output) or (codex_home / "config.toml")
    agents_target = resolve_path(args.agents_target) or (codex_home / "AGENTS.md")
    bitbucket_env_file = resolve_bitbucket_env_file(args)
    jira_oci_env_file = resolve_jira_oci_mcp_env_file(args)

    print(remove_bootstrap_output(output_path, "bootstrap config"))
    print(remove_bootstrap_output(agents_target, "global AGENTS.md"))
    print(remove_bootstrap_output(bitbucket_env_file, "Bitbucket PR env helper"))
    if is_generated_jira_oci_mcp_env_file(jira_oci_env_file):
        print(remove_bootstrap_output(jira_oci_env_file, "Jira OCI MCP env helper"))
    else:
        print(f"Skipped Jira OCI MCP env helper removal because {jira_oci_env_file} is not bootstrap-generated")
    generated_agents_dir = codex_home / "agents"
    if generated_agents_dir.exists():
        removed_agents = False
        for agent_file in sorted(generated_agents_dir.glob("*.toml")):
            if is_generated_agent_file(agent_file):
                print(remove_bootstrap_output(agent_file, "bootstrap-generated agent config"))
                removed_agents = True
        if removed_agents and not any(generated_agents_dir.iterdir()):
            generated_agents_dir.rmdir()
    generated_skills_dir = codex_home / "skills"
    if generated_skills_dir.exists():
        removed_skills = False
        for skill_name in AVAILABLE_SKILLS:
            skill_path = generated_skills_dir / skill_name
            if skill_path.is_symlink() and skill_path.resolve() == (repo_root / "skills" / skill_name).resolve():
                print(remove_bootstrap_output(skill_path, f"bootstrap skill link for {skill_name}"))
                removed_skills = True
        if removed_skills and not any(generated_skills_dir.iterdir()):
            generated_skills_dir.rmdir()
    env_paths = {
        resolve_mcp_env_file(args, server_name) or (codex_home / DEFAULT_MCP_ENV_FILENAMES[server_name])
        for server_name in MCP_ENV_SERVER_NAMES
    }
    for env_path in sorted(env_paths):
        if is_generated_mcp_env_file(env_path):
            print(remove_bootstrap_output(env_path, "shared stlm-mcp/mcp-dope MCP env helper"))
        else:
            print(f"Skipped shared stlm-mcp/mcp-dope MCP env helper removal because {env_path} is not bootstrap-generated")
    print("Undo mode only removes bootstrap-generated files. Existing backups are left untouched.")
    return 0


def write_requested_auth_helpers(
    args: argparse.Namespace,
    enabled_skills: set[str],
) -> list[tuple[str, Path, Path | None]]:
    results: list[tuple[str, Path, Path | None]] = []
    if "bitbucket-pr" in enabled_skills and args.bitbucket_auth_state == "needs-setup" and not bitbucket_auth_is_configured(args):
        bitbucket_env_path = resolve_bitbucket_env_file(args)
        bitbucket_base_url = args.bitbucket_base_url or DEFAULT_BITBUCKET_BASE_URL
        bitbucket_backup = write_helper_file(
            bitbucket_env_path,
            render_bitbucket_env_file(bitbucket_base_url),
        )
        results.append(("Bitbucket PR env helper", bitbucket_env_path, bitbucket_backup))
    if (
        "jira-ticket" in enabled_skills
        and args.jira_auth_state == "needs-setup"
        and args.generate_jira_oci_mcp_env
        and not env_file_values_present(resolve_jira_oci_mcp_env_file(args), JIRA_MCP_AUTH_ENV_NAMES)
    ):
        jira_env_path = resolve_jira_oci_mcp_env_file(args)
        jira_oci_base_url = args.jira_oci_base_url or DEFAULT_JIRA_OCI_BASE_URL
        jira_backup = write_helper_file(
            jira_env_path,
            render_jira_oci_mcp_env_file(jira_oci_base_url),
        )
        results.append(("Jira OCI MCP env helper", jira_env_path, jira_backup))
    return results


def missing_required_skill_auth(args: argparse.Namespace, enabled_skills: set[str]) -> list[str]:
    missing: list[str] = []
    if "bitbucket-pr" in enabled_skills and not bitbucket_auth_is_configured(args):
        missing.append("bitbucket-pr (BASE_URL, BITBUCKET_TOKEN)")
    if "jira-ticket" in enabled_skills and not jira_auth_is_configured(args):
        missing.append(
            "jira-ticket (JIRA_URL and JIRA_PERSONAL_TOKEN in ~/.env and ~/.env.jira-oci)"
        )
    return missing


def main() -> int:
    args = parse_args()
    if args.prompt:
        args = prompt_for_missing(args)

    if args.undo:
        return undo_bootstrap(args)

    enabled_mcp = resolve_enabled_mcp(args)
    missing_mcp_inputs = missing_required_mcp_inputs(args, enabled_mcp)
    if missing_mcp_inputs:
        print(
            "Default-enabled MCP servers require explicit local settings. "
            f"Missing: {', '.join(missing_mcp_inputs)}. "
            "Provide one shared `--env-file` for stlm-mcp and mcp-dope, "
            "supply the shared log directory for env-backed MCP servers, "
            "or rerun with --prompt so the script can ask for them. "
            "Disable the default-enabled MCP servers explicitly if you do not use them.",
            file=sys.stderr,
        )
        return 2

    values = build_values(args)
    config_source = resolve_path(args.config_source) or DEFAULT_CONFIG_SOURCE
    output_path = Path(values["output"])
    repo_root = Path(values["repo_root"])
    codex_home = Path(values["codex_home"])
    agents_target = resolve_path(args.agents_target) or (codex_home / "AGENTS.md")
    agents_source = repo_root / "AGENTS.md"
    enabled_skills = set(filter(None, values["enabled_skills"].split(",")))
    enabled_mcp = set(filter(None, values["enabled_mcp"].split(",")))

    unknown_skills = sorted(set(args.disable_skill) - set(AVAILABLE_SKILLS))
    unknown_mcp = sorted(set(args.disable_mcp + args.enable_mcp) - set(AVAILABLE_MCP_SERVERS))
    unknown_generated_mcp = sorted(set(args.generate_mcp_env) - set(MCP_ENV_GENERATOR_NAMES))
    if unknown_skills:
        print(f"Unknown skill names: {', '.join(unknown_skills)}", file=sys.stderr)
        return 2
    if unknown_mcp:
        print(f"Unknown MCP server names: {', '.join(unknown_mcp)}", file=sys.stderr)
        return 2
    if unknown_generated_mcp:
        print(
            f"Unknown MCP servers requested for env generation: {', '.join(unknown_generated_mcp)}",
            file=sys.stderr,
        )
        return 2
    disabled_generated_mcp = sorted(set(args.generate_mcp_env) - enabled_mcp)
    if disabled_generated_mcp:
        print(
            "Cannot generate env helpers for disabled MCP servers: "
            f"{', '.join(disabled_generated_mcp)}",
            file=sys.stderr,
        )
        return 2

    if not config_source.exists():
        print(f"Config source does not exist: {config_source}", file=sys.stderr)
        return 2
    if not agents_source.exists():
        print(f"Shared AGENTS.md does not exist: {agents_source}", file=sys.stderr)
        return 2
    enabled_skills = {skill for skill in AVAILABLE_SKILLS if skill not in set(args.disable_skill or [])}
    auth_helper_results = write_requested_auth_helpers(args, enabled_skills)
    missing_skill_auth = missing_required_skill_auth(args, enabled_skills)
    if missing_skill_auth:
        print_generated_auth_helpers(auth_helper_results, include_fill_guidance=True)
        print_auth_shell_guidance(
            args,
            zshenv_guidance_path(resolve_bitbucket_env_file(args), args.bitbucket_env_file, args.bitbucket_auth_state)
            if "bitbucket-pr" in enabled_skills
            else None,
            None,
        )
        print(
            "Enabled skills require configured auth. "
            f"Missing: {', '.join(missing_skill_auth)}. "
            "Populate those values in the current environment or in the helper files above, then rerun bootstrap. "
            "Source Bitbucket helpers from your shell init file when Bitbucket auth is missing; "
            "Jira MCP dotenv files are read directly by the Jira MCPs and the Jira script. "
            "Disable those skills explicitly if you do not use them.",
            file=sys.stderr,
        )
        return 2

    try:
        output_path.relative_to(repo_root)
        writes_into_repo = True
    except ValueError:
        writes_into_repo = False

    if writes_into_repo and not args.allow_repo_write:
        print(
            "Refusing to write a machine-specific config inside the shared repo. "
            "Choose a user-local path such as ~/.codex/config.toml or pass --allow-repo-write.",
            file=sys.stderr,
        )
        return 2

    template = config_source.read_text(encoding="utf-8")
    rendered = filter_blocks(template, enabled_skills, enabled_mcp)
    rendered = replace_optional_root(
        rendered,
        "/ABSOLUTE/PATH/TO/YOUR/M2_REPOSITORY",
        values.get("m2_repository"),
    )
    for server_name, value_key in (
        ("stlm-mcp", "stlm_mcp_env_file"),
        ("mcp-dope", "mcp_dope_env_file"),
    ):
        env_file = values.get(value_key)
        if env_file:
            rendered = replace_mcp_env_file_arg(rendered, server_name, env_file)

    for placeholder, value_key in PLACEHOLDER_MAP.items():
        replacement = values.get(value_key, "")
        if replacement:
            rendered = rendered.replace(placeholder, replacement)

    rendered = replace_setting(rendered, "model_provider", values["model_provider"])
    rendered = replace_setting(rendered, "model", values["model"])
    rendered = replace_setting(rendered, "profile", values["profile"])
    for placeholder, replacement in GENERIC_TEMPLATE_REPLACEMENTS.items():
        rendered = rendered.replace(placeholder, replacement)

    output_path.parent.mkdir(parents=True, exist_ok=True)
    backup_path = backup_existing_file(output_path)
    output_path.write_text(rendered, encoding="utf-8")
    sqlcl_setup_result: tuple[str, list[str]] | None = None
    sqlcl_setup_error: str | None = None
    try:
        sqlcl_setup_result = configure_sqlcl_saved_connection(args, values)
    except (ValueError, RuntimeError) as exc:
        sqlcl_setup_error = str(exc)
    generated_agent_files = write_generated_agent_files(repo_root, codex_home)
    skill_link_results = install_skill_links(repo_root, codex_home, enabled_skills)
    agents_message, agents_backup = install_agents_entrypoint(
        source=agents_source,
        target=agents_target,
        mode=args.agents_mode,
        repo_root=repo_root,
    )

    print(f"Wrote config: {output_path}")
    if backup_path:
        print(f"Backup created: {backup_path}")
    print(agents_message)
    if agents_backup:
        print(f"Global AGENTS.md backup created: {agents_backup}")
    for agent_name, agent_path, agent_backup in generated_agent_files:
        print(f"Generated agent config for {agent_name}: {agent_path}")
        if agent_backup:
            print(f"Agent config backup created: {agent_backup}")
    for skill_name, skill_path, skill_status in skill_link_results:
        print(f"Skill {skill_name}: {skill_status} at {skill_path}")
    print(f"Enabled skills: {', '.join(sorted(enabled_skills)) or '(none)'}")
    print(f"Enabled MCP servers: {', '.join(sorted(enabled_mcp)) or '(none)'}")
    if "chrome-devtools" in enabled_mcp:
        print(
            "Chrome DevTools MCP setup: the shared template uses the Canary channel "
            "to match the packaged MCP config."
        )
    if "mcp-atlassian-jira-sd" in enabled_mcp:
        print(
            "Jira-SD MCP prerequisite: mcp-atlassian-jira-sd reads Atlassian MCP "
            f"credentials from {Path(values['home_dir']) / '.env'}."
        )
    if "mcp-atlassian-jira-oci" in enabled_mcp:
        print(
            "Jira OCI MCP prerequisite: mcp-atlassian-jira-oci reads Atlassian MCP "
            f"credentials from {Path(values['home_dir']) / '.env.jira-oci'}."
        )
    if "mcp_shepherd" in enabled_mcp:
        print(
            "Shepherd MCP prerequisite: mcp_shepherd reads credentials from "
            f"{Path(values['home_dir']) / '.env'}."
        )
    if "centralconfluence" in enabled_mcp:
        print(
            "CentralConfluence MCP prerequisite: set required proxy environment "
            "variables before launching Codex if your network requires them, "
            "then run `codex mcp login centralconfluence` once to authorize it."
        )
    if "ots" in enabled_mcp:
        print(
            "OTS MCP prerequisite: expects OCI CLI config at "
            f"{Path(values['home_dir']) / '.oci' / 'config'} with profile oc1; "
            "the generated config grants the Codex sandbox write access to "
            f"{Path(values['home_dir']) / '.oci'} for security-token refresh."
        )
    if "sqlcl" in enabled_mcp:
        print(
            "SQLcl MCP prerequisite: install SQLcl under "
            f"{Path(values['home_dir']) / 'Downloads' / 'sqlcl'} "
            "or update the generated command path."
        )
    if sqlcl_setup_result is not None:
        sqlcl_summary, sqlcl_details = sqlcl_setup_result
        print(sqlcl_summary)
        for sqlcl_detail in sqlcl_details:
            print(sqlcl_detail)
    generated_mcp_env_files = write_generated_mcp_env_files(args, enabled_mcp, repo_root)
    for server_label, env_path, backup_path in generated_mcp_env_files:
        print(f"MCP env helper for {server_label}: {env_path}")
        if backup_path:
            print(f"MCP env helper backup created: {backup_path}")
    if generated_mcp_env_files:
        print(
            "Fill the generated MCP env helper files with the variables your environment requires "
            "before starting those MCP servers."
        )

    if auth_helper_results:
        print_generated_auth_helpers(auth_helper_results, include_fill_guidance=False)
    generated_auth_helper_labels = {helper_label for helper_label, _, _ in auth_helper_results}
    bitbucket_env_path = (
        zshenv_guidance_path(resolve_bitbucket_env_file(args), args.bitbucket_env_file, args.bitbucket_auth_state)
        if "bitbucket-pr" in enabled_skills
        else None
    )
    jira_env_path = None
    if "bitbucket-pr" in enabled_skills and "Bitbucket PR env helper" not in generated_auth_helper_labels:
        print("Bitbucket PR auth: configured.")
    if "jira-ticket" in enabled_skills and "Jira OCI MCP env helper" not in generated_auth_helper_labels:
        print("Jira Ticket auth: configured.")
    print_auth_shell_guidance(args, bitbucket_env_path, jira_env_path)

    scan_targets = [output_path, *[path for _, path, _ in generated_agent_files]]
    for raw_path in args.scan_path:
        resolved = resolve_path(raw_path)
        if resolved is not None:
            scan_targets.append(resolved)

    seen_paths: set[Path] = set()
    unresolved_paths = False
    unresolved_templates = False
    for scan_target in scan_targets:
        if scan_target in seen_paths or not scan_target.exists() or scan_target.is_dir():
            continue
        seen_paths.add(scan_target)
        content = scan_target.read_text(encoding="utf-8")
        target_path_hits, target_generic_hits = scan_placeholders(content)
        if target_path_hits:
            unresolved_paths = True
            print(
                f"Unresolved path placeholders in {scan_target}: {', '.join(target_path_hits)}",
                file=sys.stderr,
            )
        if target_generic_hits:
            unresolved_templates = True
            print(
                f"Remaining template placeholders in {scan_target}: {', '.join(target_generic_hits)}",
                file=sys.stderr,
            )

    if not unresolved_paths:
        print("No unresolved path placeholders found.")
    if unresolved_templates:
        print(
            "Template placeholders remain for values that were left blank. "
            "Fill them manually if you want a fully concrete config."
        )

    if sqlcl_setup_error:
        print(sqlcl_setup_error, file=sys.stderr)
        return 2

    return 1 if unresolved_paths else 0


if __name__ == "__main__":
    raise SystemExit(main())
